### ISSUE TITLE
fail to install chp_client by using `pip install git+https://github.com/di2ag/chp_client#egg=chp_client`

### ISSUE THREAD

**Issue by chunyuma** [di2ag/chp_client#16]
Hi @yakaboskic,

I'm Chunyu, from ARAX [RTXteam](https://github.com/RTXteam/RTX). We've integrated your `chp_client` into our module before but recently met a problem about installment (Please see [this](https://github.com/RTXteam/RTX/issues/1443) issue).

We found that by using the previous method (`pip install git+https://github.com/di2ag/chp_client#egg=chp_client`) to install this package, we got an error `ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.`

I also tried your new installment method:
```
pip3 install -r requirements.txt
python3 setup.py install 
```

However, I found two problems for this method. 

1) This method can't be put into our `requirements.txt`

2) By using this method, I got another error saying `ImportError: cannot import name 'build_query' from 'chp_client.query' (/home/ugrads/cqm5886/chp_client/chp_client/query.py)` when I tried to import build_query by using `from chp_client.query import build_query`

Could you please help us for fixing this issue? Thanks so much!

**Comment by yakaboskic** [comment]
Hi @chunyuma,

I just tried installing chp_client on a clean python 3.7 and 3.8 virtual using the git command:
```python
pip3 install git+https://github.com/di2ag/chp_client#egg=chp_client 
```
and everything worked out fine and install successfully. 

This could have been because we were pushing and editing the client on late Sunday night and if your travis build was running between like 12AM and 5AM on Monday it might have pulled an unstable version. Please try to re-run the install and let me know if you have any other issues.
